name: Lens App Auto Run

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo docker compose down
          sudo docker system prune -a -f
          sudo docker compose up --build > logs.txt &
